name: Build and deploy the TableServiceAPI container to the ACR.
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: appframeukwacr.azurecr.io
          username: ${{ secrets.ACTOR }}
          password: ${{ secrets.PSWD }}

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: appframeukwacr.azurecr.io/tableserviceapi:${{ github.sha }}
          file: ./Dockerfile
          
