# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - appframeukwacrAustraliaCentralASPReplicaTargetAPI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://appframeukwacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_bdc49fb267e742e9a1f83649823a0d4d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_074a53b893324b8ca826339b231650e7 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: appframeukwacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_bdc49fb267e742e9a1f83649823a0d4d }}/replicatargetservice:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'appframeukwacrAustraliaCentralASPReplicaTargetAPI'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_39504c0c84a64e0b920be351f00f6e16 }}
        images: 'appframeukwacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_bdc49fb267e742e9a1f83649823a0d4d }}/replicatargetservice:${{ github.sha }}'